import { 
  Tenant, Customer, Vehicle, WorkOrder, InventoryItem, 
  TireHotelRecord, Appointment, WorkshopBay, Payment, User, AutomationRule 
} from '../types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-usta',
    slug: 'usta-otomotiv',
    name: 'Usta Otomotiv & Özel Servis',
    status: 'ACTIVE',
    planId: 'PROFESSIONAL',
    branding: {
      primaryColor: '#0284c7', // Sky blue
      secondaryColor: '#0f172a',
      accentColor: '#f59e0b',
      companyName: 'Usta Otomotiv San. Tic. Ltd. Şti.',
      legalName: 'Usta Otomotiv Sanayi ve Ticaret Limited Şirketi',
      taxOffice: 'Maslak V.D.',
      taxNo: '8910234567',
      phone: '+90 (212) 555 01 23',
      email: 'bilgi@ustaotomotiv.com',
      website: 'https://ustaotomotiv.com',
      address: 'Atatürk Oto Sanayi Sitesi 2. Kısım 14. Sokak No:45',
      city: 'İstanbul / Sarıyer',
      currency: '₺',
      vatRate: 20,
      smsSenderTitle: 'USTAOTO',
    },
    featureFlags: {
      inventory: true,
      fleet: true,
      tire_hotel: true,
      einvoice: true,
      whatsapp: true,
      advanced_reports: true,
      ai_copilot: true,
    },
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'tenant-filo',
    slug: 'filo-servis',
    name: 'Filo Bakım Çözümleri A.Ş.',
    status: 'ACTIVE',
    planId: 'ENTERPRISE',
    branding: {
      primaryColor: '#10b981', // Emerald
      secondaryColor: '#064e3b',
      accentColor: '#3b82f6',
      companyName: 'Filo Bakım ve Filo Yönetim Hizmetleri A.Ş.',
      legalName: 'Filo Bakım Çözümleri Anonim Şirketi',
      taxOffice: 'Kozyatağı V.D.',
      taxNo: '3829104821',
      phone: '+90 (216) 444 89 00',
      email: 'operasyon@filobakim.com.tr',
      website: 'https://filobakim.com.tr',
      address: 'İçerenköy Mah. Değirmen Yolu Cad. No:18 Plaza Kat:4',
      city: 'İstanbul / Ataşehir',
      currency: '₺',
      vatRate: 20,
      smsSenderTitle: 'FILOBAKIM',
    },
    featureFlags: {
      inventory: true,
      fleet: true,
      tire_hotel: true,
      einvoice: true,
      whatsapp: true,
      advanced_reports: true,
      ai_copilot: true,
    },
    createdAt: '2024-11-10T10:00:00Z',
  },
  {
    id: 'tenant-lastik',
    slug: 'lastikpark',
    name: 'LastikPark & Express Bakım',
    status: 'ACTIVE',
    planId: 'PROFESSIONAL',
    branding: {
      primaryColor: '#ea580c', // Orange
      secondaryColor: '#18181b',
      accentColor: '#eab308',
      companyName: 'LastikPark Otomotiv ve Lastik Tic. Ltd. Şti.',
      legalName: 'LastikPark Hızlı Bakım ve Lastik Oteli Ltd. Şti.',
      taxOffice: 'Doğanbey V.D.',
      taxNo: '5629104839',
      phone: '+90 (312) 385 70 80',
      email: 'info@lastikpark.com',
      website: 'https://lastikpark.com',
      address: 'Ostim OSB 1230. Cadde No:88',
      city: 'Ankara / Yenimahalle',
      currency: '₺',
      vatRate: 20,
      smsSenderTitle: 'LASTIKPARK',
    },
    featureFlags: {
      inventory: true,
      fleet: false,
      tire_hotel: true,
      einvoice: false,
      whatsapp: true,
      advanced_reports: true,
      ai_copilot: false,
    },
    createdAt: '2025-02-01T08:30:00Z',
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    tenantId: 'tenant-usta',
    name: 'Ahmet Yılmaz',
    email: 'ahmet@ustaotomotiv.com',
    phone: '+90 532 100 20 30',
    role: 'TENANT_OWNER',
    status: 'ACTIVE',
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'user-2',
    tenantId: 'tenant-usta',
    name: 'Murat Danışman',
    email: 'murat@ustaotomotiv.com',
    phone: '+90 533 200 30 40',
    role: 'SERVICE_ADVISOR',
    status: 'ACTIVE',
    createdAt: '2025-01-16T09:00:00Z',
  },
  {
    id: 'user-3',
    tenantId: 'tenant-usta',
    name: 'Kemal Teknisyen (Usta)',
    email: 'kemal@ustaotomotiv.com',
    phone: '+90 535 300 40 50',
    role: 'TECHNICIAN',
    status: 'ACTIVE',
    createdAt: '2025-01-16T09:00:00Z',
  },
  {
    id: 'user-4',
    tenantId: 'tenant-usta',
    name: 'Selin Muhasebe',
    email: 'selin@ustaotomotiv.com',
    phone: '+90 536 400 50 60',
    role: 'ACCOUNTANT',
    status: 'ACTIVE',
    createdAt: '2025-01-20T09:00:00Z',
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    tenantId: 'tenant-usta',
    type: 'INDIVIDUAL',
    firstName: 'Can',
    lastName: 'Kaya',
    phone: '+90 532 999 11 22',
    email: 'cankaya@gmail.com',
    city: 'İstanbul',
    district: 'Beşiktaş',
    address: 'Levent Mah. Çamlık Cad. No:12',
    segment: 'VIP',
    discountRate: 10,
    loyaltyPoints: 350,
    ltv: 28500,
    totalSpent: 28500,
    visitCount: 6,
    lastVisitDate: '2026-08-10',
    npsScore: 10,
    optInSms: true,
    optInWhatsApp: true,
    optInEmail: true,
    notes: 'Aracına çok titiz, her zaman orijinal filtre ister.',
    createdAt: '2025-02-10T11:00:00Z'
  },
  {
    id: 'cust-2',
    tenantId: 'tenant-usta',
    type: 'CORPORATE',
    firstName: 'Mehmet',
    lastName: 'Demir',
    companyName: 'Demir Lojistik ve Ticaret A.Ş.',
    taxOffice: 'Zincirlikuyu V.D.',
    taxNoOrTc: '2840192837',
    phone: '+90 542 888 22 33',
    email: 'muhasebe@demirlojistik.com.tr',
    city: 'İstanbul',
    district: 'Şişli',
    address: 'Büyükdere Cad. Demir Plaza No:90',
    segment: 'FLEET',
    discountRate: 15,
    loyaltyPoints: 1200,
    ltv: 145000,
    totalSpent: 145000,
    visitCount: 18,
    lastVisitDate: '2026-08-18',
    npsScore: 9,
    optInSms: true,
    optInWhatsApp: true,
    optInEmail: true,
    notes: 'Filosundaki 8 araç servisimize kayıtlı.',
    createdAt: '2025-01-20T14:30:00Z'
  },
  {
    id: 'cust-3',
    tenantId: 'tenant-usta',
    type: 'INDIVIDUAL',
    firstName: 'Ayşe',
    lastName: 'Yıldız',
    phone: '+90 533 777 33 44',
    email: 'ayseyildiz@hotmail.com',
    city: 'İstanbul',
    district: 'Sarıyer',
    address: 'Tarabya Mah. Sahil Yolu No:4',
    segment: 'REGULAR',
    discountRate: 0,
    loyaltyPoints: 120,
    ltv: 9400,
    totalSpent: 9400,
    visitCount: 2,
    lastVisitDate: '2026-07-05',
    npsScore: 8,
    optInSms: true,
    optInWhatsApp: true,
    optInEmail: false,
    createdAt: '2025-06-12T10:00:00Z'
  }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    tenantId: 'tenant-usta',
    customerId: 'cust-1',
    plate: '34 VIP 77',
    vin: 'WBA3A5C59DF182934',
    make: 'BMW',
    model: '320i',
    subModel: 'M Sport Line',
    year: 2021,
    fuelType: 'BENZIN',
    transmission: 'OTOMATIK',
    color: 'Metalik Füme',
    currentMileage: 48500,
    lastServiceMileage: 48500,
    lastServiceDate: '2026-08-10',
    nextServiceMileage: 58500,
    nextServiceDate: '2027-02-10',
    inspectionExpiryDate: '2027-06-15',
    insuranceExpiryDate: '2026-11-20',
    cascoExpiryDate: '2026-11-20',
    notes: 'Seramik kaplama mevcut, yıkamada fırçasız yıkama rica edildi.',
    createdAt: '2025-02-10T11:15:00Z'
  },
  {
    id: 'veh-2',
    tenantId: 'tenant-usta',
    customerId: 'cust-2',
    fleetId: 'fleet-1',
    plate: '34 DL 1042',
    vin: 'WVWZZZ3CZNE049182',
    make: 'Volkswagen',
    model: 'Passat',
    subModel: '2.0 TDI Elegance DSG',
    year: 2022,
    fuelType: 'DIZEL',
    transmission: 'OTOMATIK',
    color: 'Derin Siyah',
    currentMileage: 112400,
    lastServiceMileage: 112400,
    lastServiceDate: '2026-08-18',
    nextServiceMileage: 127400,
    nextServiceDate: '2026-11-18',
    inspectionExpiryDate: '2027-04-10',
    notes: 'Ağır bakım (Triger seti ve DSG şanzıman yağı) yeni yapıldı.',
    createdAt: '2025-01-20T14:45:00Z'
  },
  {
    id: 'veh-3',
    tenantId: 'tenant-usta',
    customerId: 'cust-3',
    plate: '34 AY 890',
    vin: 'VF1RFA00569102934',
    make: 'Renault',
    model: 'Clio',
    subModel: '1.0 TCe Touch X-Tronic',
    year: 2023,
    fuelType: 'BENZIN',
    transmission: 'OTOMATIK',
    color: 'Alev Kırmızı',
    currentMileage: 23100,
    lastServiceMileage: 15000,
    lastServiceDate: '2025-10-10',
    nextServiceMileage: 30000,
    nextServiceDate: '2026-10-10',
    inspectionExpiryDate: '2026-09-30',
    notes: '2. Yıl Periyodik Bakım zamanı geldi.',
    createdAt: '2025-06-12T10:15:00Z'
  }
];

export const INITIAL_BAYS: WorkshopBay[] = [
  {
    id: 'bay-1',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    name: 'Lift 1 (2 Sütun - Hızlı Mekanik)',
    type: 'MEKANIK',
    status: 'OCCUPIED',
    activeWorkOrderId: 'wo-101',
    activeVehiclePlate: '34 VIP 77',
    activeTechnicianName: 'Kemal Teknisyen'
  },
  {
    id: 'bay-2',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    name: 'Lift 2 (4 Sütun - Ağır Mekanik)',
    type: 'MEKANIK',
    status: 'IDLE'
  },
  {
    id: 'bay-3',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    name: 'Bay 3 (Elektrik & Diagnostik)',
    type: 'DIAGNOSTIK',
    status: 'OCCUPIED',
    activeWorkOrderId: 'wo-102',
    activeVehiclePlate: '34 AY 890',
    activeTechnicianName: 'Emre Usta'
  },
  {
    id: 'bay-4',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    name: 'Bay 4 (Rot - Balans İstasyonu)',
    type: 'ROT_BALANS',
    status: 'IDLE'
  },
  {
    id: 'bay-5',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    name: 'Yıkama & Detaylı Hazırlık',
    type: 'YIKAMA',
    status: 'IDLE'
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    tenantId: 'tenant-usta',
    sku: 'FLT-OIL-BMW-01',
    barcode: '869012345001',
    oemCode: '11428570590',
    equivalentCodes: ['MANN-HU6004X', 'BOSCH-F026407123'],
    name: 'Yağ Filtresi (BMW 2.0 B48 Motor)',
    brand: 'Mann Filter',
    category: 'FILTRE',
    unit: 'ADET',
    warehouseLocation: 'Raf A-02/3',
    costPrice: 280,
    salePrice: 550,
    vatRate: 20,
    stockOnHand: 14,
    stockReserved: 2,
    stockAvailable: 12,
    minStockLevel: 5,
    maxStockLevel: 30,
    reorderPoint: 6,
    supplierName: 'Marmara Oto Yedek Parça',
    isActive: true
  },
  {
    id: 'inv-2',
    tenantId: 'tenant-usta',
    sku: 'OIL-MOTUL-5W30-4L',
    barcode: '337465023901',
    oemCode: 'MOTUL-8100-X-CLEAN',
    name: 'Motul 8100 X-Clean EFE 5W-30 Tam Sentetik Motor Yağı (4 Litre)',
    brand: 'Motul',
    category: 'YAG_SIVI',
    unit: 'ADET',
    warehouseLocation: 'Sıvı Deposu B-1',
    costPrice: 950,
    salePrice: 1650,
    vatRate: 20,
    stockOnHand: 22,
    stockReserved: 3,
    stockAvailable: 19,
    minStockLevel: 10,
    maxStockLevel: 50,
    reorderPoint: 12,
    supplierName: 'Motul Türkiye Distribütörü',
    isActive: true
  },
  {
    id: 'inv-3',
    tenantId: 'tenant-usta',
    sku: 'BRK-PAD-BMW-FR',
    barcode: '400663229012',
    oemCode: '34116850885',
    equivalentCodes: ['TRW-GDB2091', 'BREMBO-P06088'],
    name: 'Ön Fren Balata Takımı (BMW G20 / F30)',
    brand: 'Brembo',
    category: 'FREN',
    unit: 'TAKIM',
    warehouseLocation: 'Raf F-10/1',
    costPrice: 1400,
    salePrice: 2600,
    vatRate: 20,
    stockOnHand: 3, // Low stock!
    stockReserved: 2,
    stockAvailable: 1,
    minStockLevel: 4,
    maxStockLevel: 15,
    reorderPoint: 4,
    supplierName: 'Brembo Yedek Parça A.Ş.',
    isActive: true
  },
  {
    id: 'inv-4',
    tenantId: 'tenant-usta',
    sku: 'FLT-AIR-VAG-02',
    barcode: '869012345009',
    oemCode: '5Q0129620B',
    name: 'Hava Filtresi (VW Passat / Golf 7 2.0 TDI)',
    brand: 'Bosch',
    category: 'FILTRE',
    unit: 'ADET',
    warehouseLocation: 'Raf A-04/1',
    costPrice: 220,
    salePrice: 420,
    vatRate: 20,
    stockOnHand: 18,
    stockReserved: 0,
    stockAvailable: 18,
    minStockLevel: 6,
    maxStockLevel: 30,
    reorderPoint: 8,
    supplierName: 'Marmara Oto Yedek Parça',
    isActive: true
  }
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-101',
    workOrderNo: 'WO-2026-0042',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    customerId: 'cust-1',
    vehicleId: 'veh-1',
    advisorId: 'user-2',
    advisorName: 'Murat Danışman',
    technicianId: 'user-3',
    technicianName: 'Kemal Teknisyen',
    bayId: 'bay-1',
    bayName: 'Lift 1 (2 Sütun - Hızlı Mekanik)',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    serviceType: 'PERIYODIK_BAKIM',
    intake: {
      id: 'intk-101',
      workOrderId: 'wo-101',
      mileageIn: 48500,
      fuelLevelPercent: 75,
      hasSpareTire: true,
      hasJack: true,
      hasRegistrationDoc: true,
      keyCount: 2,
      customerComplaints: '50.000 km periyodik bakımı yapılacak. Ön frenden hafif sürtünme sesi geliyor.',
      damagePoints: [
        {
          id: 'dmg-1',
          view: 'LEFT',
          xPercent: 72,
          yPercent: 45,
          type: 'SCRATCH',
          severity: 'LIGHT',
          note: 'Sol arka çamurlukta 3 cm yüzeysel çizik'
        },
        {
          id: 'dmg-2',
          view: 'FRONT',
          xPercent: 30,
          yPercent: 60,
          type: 'DENT',
          severity: 'LIGHT',
          note: 'Ön tampon sağ altta taş izi'
        }
      ],
      photos: [
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=60'
      ],
      completedAt: '2026-08-21T09:30:00Z',
      advisorName: 'Murat Danışman'
    },
    inspection: {
      id: 'insp-101',
      workOrderId: 'wo-101',
      technicianId: 'user-3',
      technicianName: 'Kemal Teknisyen',
      completedAt: '2026-08-21T10:15:00Z',
      overallSummary: 'Periyodik bakım yapıldı, ön fren balataları %15 seviyesinde, acil değişim tavsiye edildi.',
      items: [
        {
          id: 'mpi-1',
          category: 'MOTOR',
          title: 'Motor Yağı & Yağ Filtresi',
          condition: 'ATTENTION',
          description: 'Yağ ömrü dolmuş, kararma mevcut. Değişim şart.'
        },
        {
          id: 'mpi-2',
          category: 'FREN',
          title: 'Ön Fren Balataları & Diskler',
          condition: 'URGENT',
          description: 'Ön balata kalınlığı 2.1 mm altına inmiş, disk yüzeyinde hafif fatura var.',
          recommendedPartName: 'Brembo Ön Fren Balata Takımı',
          estimatedPartCost: 2600,
          estimatedLaborCost: 800
        },
        {
          id: 'mpi-3',
          category: 'SIVILAR',
          title: 'Fren Hidroliği & Antifriz Derecesi',
          condition: 'GOOD',
          description: 'Antifriz -35°C koruma seviyesinde, hidrolik nem oranı %1 altında (mükemmel).'
        },
        {
          id: 'mpi-4',
          category: 'LASTIK',
          title: 'Lastik Diş Derinliği & Basınçlar',
          condition: 'GOOD',
          description: '4 lastik ortalama 6.2 mm diş derinliğinde, basınçlar 34 PSI ayarlandı.'
        }
      ]
    },
    estimate: {
      id: 'est-101',
      workOrderId: 'wo-101',
      revisionNumber: 1,
      subtotalParts: 4800,
      subtotalLabor: 1600,
      subtotalSupplies: 300,
      totalDiscount: 670,
      totalVat: 1206,
      grandTotal: 7236,
      approvedTotal: 7236,
      customerApprovalToken: 'appr-token-bmw-320',
      status: 'FULLY_APPROVED',
      approvedAt: '2026-08-21T10:45:00Z',
      items: [
        {
          id: 'ei-1',
          type: 'PART',
          sku: 'OIL-MOTUL-5W30-4L',
          name: 'Motul 8100 X-Clean 5W-30 Motor Yağı (5L)',
          quantity: 1.25,
          unit: 'ADET',
          unitCost: 950,
          unitPrice: 1650,
          discountRate: 10,
          vatRate: 20,
          totalPrice: 2227.5,
          status: 'APPROVED'
        },
        {
          id: 'ei-2',
          type: 'PART',
          sku: 'FLT-OIL-BMW-01',
          name: 'Yağ Filtresi Mann Orijinal',
          quantity: 1,
          unit: 'ADET',
          unitCost: 280,
          unitPrice: 550,
          discountRate: 10,
          vatRate: 20,
          totalPrice: 594,
          status: 'APPROVED'
        },
        {
          id: 'ei-3',
          type: 'PART',
          sku: 'BRK-PAD-BMW-FR',
          name: 'Brembo Ön Fren Balata Takımı',
          quantity: 1,
          unit: 'TAKIM',
          unitCost: 1400,
          unitPrice: 2600,
          discountRate: 10,
          vatRate: 20,
          totalPrice: 2808,
          status: 'APPROVED'
        },
        {
          id: 'ei-4',
          type: 'LABOR',
          name: 'Periyodik Bakım ve Fren Balatası Değişimi İşçiliği',
          quantity: 1,
          unit: 'SAAT',
          unitCost: 400,
          unitPrice: 1600,
          discountRate: 10,
          vatRate: 20,
          totalPrice: 1728,
          status: 'APPROVED'
        }
      ],
      createdAt: '2026-08-21T10:30:00Z'
    },
    items: [],
    totalAmount: 7236,
    paidAmount: 0,
    paymentStatus: 'UNPAID',
    estimatedDeliveryDate: '2026-08-21T17:00:00',
    createdAt: '2026-08-21T09:15:00Z',
    updatedAt: '2026-08-21T11:00:00Z'
  },
  {
    id: 'wo-102',
    workOrderNo: 'WO-2026-0043',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    customerId: 'cust-3',
    vehicleId: 'veh-3',
    advisorId: 'user-2',
    advisorName: 'Murat Danışman',
    technicianId: 'user-3',
    technicianName: 'Kemal Teknisyen',
    bayId: 'bay-3',
    bayName: 'Bay 3 (Elektrik & Diagnostik)',
    status: 'AWAITING_APPROVAL',
    priority: 'NORMAL',
    serviceType: 'ELEKTRIK_ELEKTRONIK',
    totalAmount: 3450,
    paidAmount: 0,
    paymentStatus: 'UNPAID',
    items: [],
    estimate: {
      id: 'est-102',
      workOrderId: 'wo-102',
      revisionNumber: 1,
      subtotalParts: 2100,
      subtotalLabor: 900,
      subtotalSupplies: 150,
      totalDiscount: 0,
      totalVat: 630,
      grandTotal: 3780,
      approvedTotal: 0,
      customerApprovalToken: 'appr-clio-ayse-yildiz',
      status: 'SENT',
      items: [
        {
          id: 'ei-10',
          type: 'PART',
          name: 'Varta 12V 60Ah EFB Start-Stop Akü',
          quantity: 1,
          unit: 'ADET',
          unitCost: 1500,
          unitPrice: 2100,
          discountRate: 0,
          vatRate: 20,
          totalPrice: 2520,
          status: 'PENDING'
        },
        {
          id: 'ei-11',
          type: 'LABOR',
          name: 'Diagnostik Akü Kodlama ve Değişim İşçiliği',
          quantity: 1,
          unit: 'SAAT',
          unitCost: 300,
          unitPrice: 900,
          discountRate: 0,
          vatRate: 20,
          totalPrice: 1080,
          status: 'PENDING'
        }
      ],
      createdAt: '2026-08-21T11:20:00Z'
    },
    estimatedDeliveryDate: '2026-08-21T18:00:00',
    createdAt: '2026-08-21T10:45:00Z',
    updatedAt: '2026-08-21T11:25:00Z'
  },
  {
    id: 'wo-103',
    workOrderNo: 'WO-2026-0041',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    customerId: 'cust-2',
    vehicleId: 'veh-2',
    advisorId: 'user-2',
    advisorName: 'Murat Danışman',
    status: 'READY_FOR_PICKUP',
    priority: 'NORMAL',
    serviceType: 'PERIYODIK_BAKIM',
    totalAmount: 14850,
    paidAmount: 14850,
    paymentStatus: 'PAID',
    items: [],
    estimatedDeliveryDate: '2026-08-21T15:00:00',
    createdAt: '2026-08-20T14:00:00Z',
    updatedAt: '2026-08-21T14:30:00Z'
  }
];

export const INITIAL_TIRE_HOTEL: TireHotelRecord[] = [
  {
    id: 'th-1',
    tenantId: 'tenant-usta',
    customerId: 'cust-1',
    customerName: 'Can Kaya',
    customerPhone: '+90 532 999 11 22',
    vehicleId: 'veh-1',
    vehiclePlate: '34 VIP 77',
    brand: 'Michelin',
    model: 'Pilot Alpin 5 (Kışlık)',
    tireSize: '225/45 R18',
    season: 'WINTER',
    dotCode: '3823',
    treadDepthFL: 6.8,
    treadDepthFR: 6.7,
    treadDepthRL: 7.1,
    treadDepthRR: 7.0,
    hasRims: true,
    rimCondition: 'Orijinal BMW M Jantlı, çiziksiz',
    shelfLocation: 'Lastik Deposu - Blok A, Raf 03/2',
    intakeDate: '2026-04-12',
    expiryDate: '2026-11-15',
    status: 'STORED',
    notes: 'Kış sezonunda montaj için 15 Kasım randevusu hedeflendi.'
  },
  {
    id: 'th-2',
    tenantId: 'tenant-usta',
    customerId: 'cust-2',
    customerName: 'Demir Lojistik / Mehmet Demir',
    customerPhone: '+90 542 888 22 33',
    vehicleId: 'veh-2',
    vehiclePlate: '34 DL 1042',
    brand: 'Continental',
    model: 'WinterContact TS 870 P',
    tireSize: '215/55 R17',
    season: 'WINTER',
    dotCode: '4022',
    treadDepthFL: 5.2,
    treadDepthFR: 5.3,
    treadDepthRL: 5.5,
    treadDepthRR: 5.4,
    hasRims: false,
    shelfLocation: 'Lastik Deposu - Blok B, Raf 01/4',
    intakeDate: '2026-04-05',
    expiryDate: '2026-11-01',
    status: 'STORED'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    customerId: 'cust-1',
    customerName: 'Can Kaya',
    customerPhone: '+90 532 999 11 22',
    vehiclePlate: '34 VIP 77',
    vehicleMakeModel: 'BMW 320i M Sport',
    serviceType: 'Periyodik Bakım + Fren Kontrolü',
    requestedDate: '2026-08-21',
    requestedTime: '09:00',
    status: 'IN_SERVICE',
    customerNotes: 'Sabah erken bırakacağım, öğleden sonra teslim alabilir miyim?',
    createdAt: '2026-08-19T10:00:00Z'
  },
  {
    id: 'apt-2',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    customerId: 'cust-3',
    customerName: 'Ayşe Yıldız',
    customerPhone: '+90 533 777 33 44',
    vehiclePlate: '34 AY 890',
    vehicleMakeModel: 'Renault Clio 1.0 TCe',
    serviceType: 'Akü & Elektrik Arızası',
    requestedDate: '2026-08-21',
    requestedTime: '10:30',
    status: 'ARRIVED',
    customerNotes: 'Start-stop çalışmıyor, sabah zor marş aldı.',
    createdAt: '2026-08-20T16:20:00Z'
  },
  {
    id: 'apt-3',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    customerId: 'cust-2',
    customerName: 'Mehmet Demir',
    customerPhone: '+90 542 888 22 33',
    vehiclePlate: '34 DL 9901',
    vehicleMakeModel: 'Ford Transit Custom',
    serviceType: '120.000 Km Ağır Bakım',
    requestedDate: '2026-08-22',
    requestedTime: '09:00',
    status: 'CONFIRMED',
    customerNotes: 'Filo aracı, faturası Demir Lojistik adına kesilecek.',
    createdAt: '2026-08-21T08:00:00Z'
  }
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    tenantId: 'tenant-usta',
    branchId: 'branch-1',
    workOrderId: 'wo-103',
    customerId: 'cust-2',
    customerName: 'Demir Lojistik ve Ticaret A.Ş.',
    amount: 14850,
    method: 'BANK_TRANSFER',
    status: 'COMPLETED',
    receiptNo: 'MK-2026-0038',
    receivedBy: 'Selin Muhasebe',
    createdAt: '2026-08-21T14:35:00Z',
    notes: 'Garanti Bankası hesabına havale'
  }
];

export const INITIAL_AUTOMATIONS: AutomationRule[] = [
  {
    id: 'auto-1',
    tenantId: 'tenant-usta',
    name: 'İş Emri Teslime Hazır Olduğunda Müşteriye WhatsApp Gönder',
    eventTrigger: 'WORK_ORDER_STATUS_CHANGED',
    conditionField: 'status',
    conditionValue: 'READY_FOR_PICKUP',
    actionType: 'SEND_WHATSAPP',
    templateText: 'Sayın {CUSTOMER_NAME}, {PLATE} plakalı aracınızın servis işlemleri tamamlanmış olup teslime hazırdır. Detaylı servis formu ve konumuz: {TRACKING_LINK}',
    isActive: true
  },
  {
    id: 'auto-2',
    tenantId: 'tenant-usta',
    name: 'Teklif Hazırlandığında Dijital Onay Linki Gönder',
    eventTrigger: 'ESTIMATE_APPROVED',
    actionType: 'SEND_WHATSAPP',
    templateText: 'Sayın {CUSTOMER_NAME}, aracınız için hazırlanan servis teklifini incelemek ve kalem kalem onaylamak için lütfen tıklayınız: {APPROVAL_LINK}',
    isActive: true
  },
  {
    id: 'auto-3',
    tenantId: 'tenant-usta',
    name: 'Kritik Stok Uyarısı (Satın Alma Görevi Oluştur)',
    eventTrigger: 'INVENTORY_LOW',
    actionType: 'CREATE_TASK',
    templateText: '{ITEM_NAME} stoğu kritik seviyenin ({MIN_STOCK}) altına düştü. Güncel stok: {CURRENT_STOCK}. Sipariş verilmeli.',
    isActive: true
  }
];
